

services:

  # TRAEFIK

  reverse-proxy:

      image: traefik:v3.2
      container_name: reverse-proxy
      command:
          - "--api.dashboard=true"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--providers.docker.network=proxy-network"
          - "--entrypoints.web.address=:80"
          - "--log.level=INFO"
          - "--accesslog=true"
      ports:
        - "80:80"       # HTTP
        - "8080:8080"   # Traefik Dashboard
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - proxy-network
      labels:
        - "traefik.enable=true"



  # FRONTEND

  frontend:
    build:
      context: ./react-demo
      dockerfile: Dockerfile
    image: frontend-image
    container_name: energy-frontend
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - person-backend
      - device-backend


  # PERSON MICROSERVICE

  person-db:
    image: mysql:8.0
    container_name: person-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: person_db
    ports:
      - "3307:3306"
    volumes:
      - person-mysql:/var/lib/mysql
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 30s

  person-backend:
    build:
      context: ./demoperson
      dockerfile: Dockerfile
    image: person-backend-image
    container_name: person-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://person-db:3306/person_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081

    depends_on:
      person-db:
        condition: service_healthy
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.person-service.rule=PathPrefix(`/api/auth`) || PathPrefix(`/api/people`) || PathPrefix(`/swagger-ui-person.html`) || PathPrefix(`/swagger-ui`) || PathPrefix(`/v3/api-docs-person`)"
      - "traefik.http.routers.person-service.service=person-service"
      - "traefik.http.services.person-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.person-service.middlewares=strip-api"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"


  # DEVICE MICROSERVICE

  device-db:
    image: mysql:8.0
    container_name: device-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: device_db

    ports:
      - "3308:3306"
    volumes:
      - device-mysql:/var/lib/mysql
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 30s

  device-backend:
    build:
      context: ./demodevice
      dockerfile: Dockerfile
    image: device-backend-image
    container_name: device-backend
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://device-db:3306/device_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8082

    depends_on:
      device-db:
        condition: service_healthy
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.device-service.rule=PathPrefix(`/api/devices`) || PathPrefix(`/swagger-ui-device.html`) || PathPrefix(`/swagger-ui-device`) || PathPrefix(`/v3/api-docs-device`)"
      - "traefik.http.routers.device-service.service=device-service"
      - "traefik.http.services.device-service.loadbalancer.server.port=8082"
      - "traefik.http.routers.device-service.middlewares=strip-api"


volumes:
  person-mysql:
  device-mysql:


# NETWORK

networks:
  proxy-network:
    external: false
    name: proxy-network
    driver: bridge