spring.application.name=monitoring
server.port=8083

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3309/monitoring_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=anna
spring.rabbitmq.password=ann
spring.rabbitmq.virtual-host=/

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.amqp=INFO

# OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs-monitoring
springdoc.swagger-ui.path=/swagger-ui-monitoring.html
springdoc.swagger-ui.use-root-path=true
